services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount the entire project directory to the container
    ports:
      - "8000:8000"  # Adjust this based on your app's port
    # environment:
    #   - PYTHONUNBUFFERED=1  # Helps to see logs in real time
  
  # report-server:
  #   image: node:18
  #   container_name: report-server-two
  #   volumes:
  #     - ./reports:/app/playwright-report  # Mount the reports directory
  #   working_dir: /app/playwright-report
  #   command: ["http-server", "-p", "3000"]
  #   ports:
  #     - "3000:3000"  # Expose port 8080
    
  #   entrypoint: ["/bin/sh", "-c", "npm install -g http-server && http-server -p 3000"]