name: Playwright Tests Execution

on:
  workflow_dispatch:

jobs:
  QA-Api-Challenge:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Checkout app repo
        uses: actions/checkout@v3
        with:
          repository: openinnovationai/recruiting-qa-challenge
          path: app-repo

      - name: Start Docker Compose App
        working-directory: app-repo
        run: |
          docker-compose up -d
          docker-compose logs

      - name: Checkout Playwright repo
        uses: actions/checkout@v3
        with:
          repository: saifa1i/OpenInnovationAI-QAChallenge
          path: playwright-repo

      - name: Set up Node.js and install Playwright dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Playwright dependencies
        run: |
          cd playwright-repo
          npm install

      - name: Run Playwright tests
        run: |
          cd playwright-repo
          npx playwright test --reporter=html

      - name: List Directory Contents
        if: always()
        run: |
          ls -la playwright-repo/playwright-report  # List all files and directories

      - name: Compress Playwright report
        if: always()
        run: |
          zip -r playwright-report.zip playwright-repo/playwright-report  # Zipping the report directory

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report.zip
          
      - name: Stop Docker Compose
        if: always()
        working-directory: app-repo
        run: |
          docker-compose down
