name: Playwright Tests Execution

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout first repo (app)
      - name: Checkout app repo
        uses: actions/checkout@v3
        with:
          repository: openinnovationai/recruiting-qa-challenge
          path: app-repo

      # Step 2: Build and start the app using Docker Compose
      - name: Start Docker Compose App
        working-directory: app-repo
        run: |
          docker-compose up

      # Step 3: Checkout second repo (Playwright tests)
      - name: Checkout Playwright repo
        uses: actions/checkout@v3
        with:
          repository: saifa1i/OpenInnovationAI-QAChallenge
          path: playwright-repo

      # Step 4: Install dependencies for Playwright tests
      - name: Set up Node.js and install Playwright dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Playwright dependencies
        run: |
          cd playwright-repo
          npm install

      # Step 5: Run Playwright tests inside the same container where the app is running
      - name: Run Playwright tests
        run: |
          cd playwright-repo
          npx playwright test

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: ./playwright-report
          
      # Step 6: Stop and clean up Docker containers after tests
      - name: Stop Docker Compose
        working-directory: app-repo
        run: |
          docker-compose down
